# This docker-compose.yaml file is not used currently

version: '3.4'

services:
  db:
    image: mysql:5.7
    command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'

  backend:
    build: ./backend
    image: 312-bc/versus-api # name of the image that gets automatically created by 'docker-compose build' command
    restart: always
    volumes:
      - ./backend:/backend
    env_file:
      - .env.test
    depends_on:
      - db
    links:
      - db
    ports:
      - '8000:8080'

  frontend:
    build: ./frontend
    image: 312-bc/versus-ui # name of the image that gets automatically created by 'docker-compose build' command
    restart: always
    depends_on:
      - backend
    links:
      - backend
    ports:
      - '3000:8080'
