apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: "http"
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  type: {{ .Values.serviceType }}
